package httpapi

import (
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"sort"
	"strings"
	"time"

	"github.com/lightshipHQ/lightship/internal/auth"
	"github.com/lightshipHQ/lightship/internal/schema"
	"github.com/lightshipHQ/lightship/internal/store"
)

// The provisioning surface. Users left the config file because that file grew with the organisation
// while the thing worth reviewing in git — the set of access rules — did not. What is here is the
// replacement, and it is deliberately small: create, read, update, delete, and set attributes.
//
// Every route is admin-only and every mutation is audited. Setting an attribute is the single most
// privilege-relevant call in the product: whoever sets tenant_id decides what a caller sees, which
// is why the audit row carries the values and not just the fact of the change.

// decode reads a JSON body under a size cap, so a malformed or hostile request cannot cost memory.
func decode(w http.ResponseWriter, r *http.Request, v any) bool {
	return decodeBody(w, r, v, false)
}

// decodeOptional is decode for a request whose body may legitimately be absent.
//
// It exists because "is there a body" cannot be answered by Content-Length: a chunked request
// reports -1, so testing for a positive length silently skips a body that was in fact sent. Ask the
// decoder instead.
func decodeOptional(w http.ResponseWriter, r *http.Request, v any) bool {
	return decodeBody(w, r, v, true)
}

func decodeBody(w http.ResponseWriter, r *http.Request, v any, optional bool) bool {
	dec := json.NewDecoder(http.MaxBytesReader(w, r.Body, 64<<10))
	dec.DisallowUnknownFields()
	if err := dec.Decode(v); err != nil {
		if optional && errors.Is(err, io.EOF) {
			return true
		}
		writeJSON(w, http.StatusBadRequest, map[string]any{"error": "malformed request: " + err.Error()})
		return false
	}
	return true
}

// storeErr maps a provisioning error to a status code. A script acting on 404 when it should act on
// 409 misprovisions silently, so the distinction is worth keeping.
func storeErr(w http.ResponseWriter, err error) {
	switch {
	case errors.Is(err, store.ErrNotFound):
		writeJSON(w, http.StatusNotFound, map[string]any{"error": err.Error()})
	case errors.Is(err, store.ErrExists), errors.Is(err, store.ErrModelConflict):
		writeJSON(w, http.StatusConflict, map[string]any{"error": err.Error()})
	case errors.Is(err, store.ErrUnknownRole), errors.Is(err, auth.ErrInvalidHash):
		writeJSON(w, http.StatusBadRequest, map[string]any{"error": err.Error()})
	case errors.Is(err, store.ErrProtected):
		writeJSON(w, http.StatusForbidden, map[string]any{"error": err.Error()})
	default:
		writeJSON(w, http.StatusInternalServerError, map[string]any{"error": "could not complete request"})
	}
}

// checkAttrs keeps attribute names usable as user.<name> policy references. Valid names are added
// to the policy vocabulary by the same transaction that stores their first value.
func checkAttrs(w http.ResponseWriter, keys []string) bool {
	var bad []string
	for _, k := range keys {
		if !schema.ValidIdent(k) {
			bad = append(bad, k)
		}
	}
	if len(bad) > 0 {
		sort.Strings(bad)
		writeJSON(w, http.StatusBadRequest, map[string]any{
			"error": "attribute names must be plain identifiers: " + strings.Join(bad, ", "),
		})
		return false
	}
	return true
}

// Imported hashes must use the bounded canonical profile generated by `lightship hash`.
func checkHash(w http.ResponseWriter, hash string) bool {
	if hash != "" && auth.ValidateHash(hash) != nil {
		writeJSON(w, http.StatusBadRequest, map[string]any{
			"error": "password_hash must use the Argon2id profile generated by `lightship hash`"})
		return false
	}
	return true
}

// ── users ───────────────────────────────────────────────────────────────────

// createUser provisions a user and, unless the caller supplied a hash, the password itself.
//
// Generating it here is what stops an admin knowing every user's password forever. The old shape —
// the admin runs `lightship hash` and posts the result — meant the person who provisioned an
// account could sign in as its owner indefinitely, and every audit row that session wrote named the
// wrong actor. Now the admin reads a generated password once, hands it over, and the flag below
// makes it useless the moment it has been used: this is the Gitea and Forgejo shape, and it is the
// only version of provisioning that the audit log's central claim survives.
//
// The password travels outbound exactly once, in this response, and only its argon2id hash is
// stored — the same handling an API key token gets. That is not the boundary `password_hash`
// protects, which is about plaintext arriving *inbound* from an admin who would then know it.
func (s *Server) createUser(w http.ResponseWriter, r *http.Request) {
	var body struct {
		Username     string            `json:"username"`
		PasswordHash string            `json:"password_hash"`
		Attributes   map[string]string `json:"attributes"`
		Roles        []string          `json:"roles"`
		// A pointer so that omitting it means the default rather than false. The default is true,
		// because the common case is a person being enrolled and the expensive mistake is a shared
		// password nobody is ever forced to replace.
		MustChangePassword *bool `json:"must_change_password"`
	}
	if !decode(w, r, &body) {
		return
	}
	if body.Username == "" {
		writeJSON(w, http.StatusBadRequest, map[string]any{"error": "username is required"})
		return
	}
	if !checkHash(w, body.PasswordHash) || !checkAttrs(w, keys(body.Attributes)) {
		return
	}
	mustChange := body.MustChangePassword == nil || *body.MustChangePassword

	// No hash supplied: generate the credential rather than leave the account unusable. The
	// generator is the bootstrap admin's, because the two credentials are handed over the same way
	// and should be the same string.
	hash, generated := body.PasswordHash, ""
	if hash == "" {
		pw, err := store.GeneratePassword()
		if err != nil {
			writeJSON(w, http.StatusInternalServerError,
				map[string]any{"error": "could not generate a password"})
			return
		}
		h, err := auth.Hash(pw)
		if err != nil {
			writeJSON(w, http.StatusInternalServerError,
				map[string]any{"error": "could not generate a password"})
			return
		}
		hash, generated = h, pw
	}

	if err := s.st.CreateUser(r.Context(), body.Username, hash,
		body.Attributes, body.Roles, mustChange); err != nil {
		storeErr(w, err)
		return
	}
	// The audit row records that a password was generated and that the user must change it, never
	// the password. What an operator needs to reconstruct later is who was enrolled on what terms.
	s.audit(r, "user.create", "", map[string]any{
		"username": body.Username, "roles": body.Roles, "attributes": body.Attributes,
		"password_generated": generated != "", "must_change_password": mustChange})
	out := map[string]any{"username": body.Username}
	if generated != "" {
		// The only time this password is readable. Only its argon2id hash is stored, so an admin
		// who loses it reprovisions rather than recovers it.
		out["password"] = generated
	}
	writeJSON(w, http.StatusCreated, out)
}

func (s *Server) listUsers(w http.ResponseWriter, r *http.Request) {
	users, err := s.st.ListUsers(r.Context())
	if err != nil {
		storeErr(w, err)
		return
	}
	writeJSON(w, http.StatusOK, map[string]any{"users": users})
}

func (s *Server) getUser(w http.ResponseWriter, r *http.Request) {
	u, err := s.st.GetUser(r.Context(), r.PathValue("username"))
	if err != nil {
		storeErr(w, err)
		return
	}
	writeJSON(w, http.StatusOK, u)
}

// updateUser sets password and roles. Both fields are pointers so that omitting one leaves it
// alone, while sending an empty roles list genuinely removes every role — the supported way to
// suspend a caller without deleting the audit history attached to their name.
func (s *Server) updateUser(w http.ResponseWriter, r *http.Request) {
	var body struct {
		PasswordHash *string   `json:"password_hash"`
		Roles        *[]string `json:"roles"`
	}
	if !decode(w, r, &body) {
		return
	}
	if body.PasswordHash != nil && !checkHash(w, *body.PasswordHash) {
		return
	}
	username := r.PathValue("username")
	revoked, err := s.st.UpdateUser(r.Context(), username, body.PasswordHash, body.Roles)
	if err != nil {
		storeErr(w, err)
		return
	}
	detail := map[string]any{"username": username}
	if body.Roles != nil {
		detail["roles"] = *body.Roles
	}
	if body.PasswordHash != nil {
		detail["password_changed"] = true
		detail["sessions_revoked"] = revoked
	}
	s.audit(r, "user.update", "", detail)
	out := map[string]any{"username": username}
	if body.PasswordHash != nil {
		out["sessions_revoked"] = revoked
	}
	writeJSON(w, http.StatusOK, out)
}

func (s *Server) deleteUser(w http.ResponseWriter, r *http.Request) {
	username := r.PathValue("username")
	if err := s.st.DeleteUser(r.Context(), username); err != nil {
		storeErr(w, err)
		return
	}
	// Sessions and keys cascade with the row, so this is revocation and not a request to expire.
	s.audit(r, "user.delete", "", map[string]any{"username": username})
	writeJSON(w, http.StatusOK, map[string]any{"deleted": username})
}

// patchAttributes updates the attributes named in the body and leaves the rest alone, with an
// explicit null removing one — JSON Merge Patch semantics. Removal has to be expressible: an
// attribute that could only ever be set would be a grant nobody could narrow.
//
// There is deliberately no whole-set replace beside it. Two ways to write the most
// privilege-relevant field in the product is one more than the number of behaviours worth
// reasoning about, and a replace sent with a key accidentally omitted silently revokes it.
func (s *Server) patchAttributes(w http.ResponseWriter, r *http.Request) {
	var attrs map[string]*string
	if !decode(w, r, &attrs) {
		return
	}
	if len(attrs) == 0 {
		writeJSON(w, http.StatusBadRequest, map[string]any{"error": "no attributes given"})
		return
	}
	if !checkAttrs(w, keys(attrs)) {
		return
	}
	username := r.PathValue("username")
	before, err := s.st.GetUser(r.Context(), username)
	if err != nil {
		storeErr(w, err)
		return
	}
	after, err := s.st.PatchAttributes(r.Context(), username, attrs)
	if err != nil {
		storeErr(w, err)
		return
	}
	// Before and after in full, not the patch: this call decides what rows the user can see, and a
	// delta is not enough to reconstruct who could see what, when.
	s.audit(r, "attribute.set", "", map[string]any{
		"username": username, "before": before.Attributes, "after": after})
	writeJSON(w, http.StatusOK, map[string]any{"username": username, "attributes": after})
}

// keys is the set of names a request wants to touch, whatever the value type carrying them.
func keys[V any](m map[string]V) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	return out
}

// ── api keys ────────────────────────────────────────────────────────────────

// createKey is the one route on this file open to every caller, because a key is how the API and an
// MCP client are reached and a product consumed that way cannot make every user ask an admin for a
// credential.
//
// A key is always minted for the authenticated caller, never for anyone else. Minting on behalf of
// another principal would be a silent impersonation primitive: every audit row such a key writes
// names the target user, so an admin could act as anyone with nothing in the log to show it — the
// exact failure the audit trail exists to rule out. Onboarding therefore runs the other way: an
// admin creates the user, and the user signs in and mints their own key. Self-service escalates
// nothing, because a key grants exactly what its user's roles grant, resolved fresh on every
// request.
func (s *Server) createKey(w http.ResponseWriter, r *http.Request) {
	var body struct {
		Name      string `json:"name"`
		ExpiresIn string `json:"expires_in"`
	}
	if !decode(w, r, &body) {
		return
	}
	if body.Name == "" {
		writeJSON(w, http.StatusBadRequest, map[string]any{"error": "name is required"})
		return
	}

	sess := sessionFrom(r.Context())
	expires, err := keyExpiry(body.ExpiresIn, s.keyExpiry, time.Now())
	if err != nil {
		writeJSON(w, http.StatusBadRequest, map[string]any{"error": err.Error()})
		return
	}

	token, err := auth.NewKey()
	if err != nil {
		writeJSON(w, http.StatusInternalServerError, map[string]any{"error": "could not mint key"})
		return
	}
	id, err := s.st.CreateKey(r.Context(), body.Name, token, sess.Username, expires)
	if err != nil {
		storeErr(w, err)
		return
	}
	s.audit(r, "key.create", "", map[string]any{"key_id": id, "name": body.Name})
	// The only time the token is ever readable. Only its sha256 is stored.
	writeJSON(w, http.StatusCreated, map[string]any{
		"id": id, "name": body.Name, "username": sess.Username, "token": token})
}

type keyExpiryPolicy struct {
	Default time.Duration
	Maximum time.Duration
}

func keyExpiry(expiresIn string, policy keyExpiryPolicy, now time.Time) (*time.Time, error) {
	if expiresIn == "" && policy.Default > 0 {
		expiresIn = policy.Default.String()
	}
	if expiresIn == "" {
		return nil, nil
	}
	d, err := time.ParseDuration(expiresIn)
	if err != nil || d <= 0 {
		return nil, errors.New("expires_in must be a positive Go duration, e.g. \"720h\"")
	}
	if policy.Maximum > 0 && d > policy.Maximum {
		return nil, fmt.Errorf("API keys may live for at most %s", policy.Maximum)
	}
	t := now.Add(d)
	return &t, nil
}

// listKeys shows a caller their own keys, and an admin every key.
func (s *Server) listKeys(w http.ResponseWriter, r *http.Request) {
	keys, err := s.st.ListKeys(r.Context(), scope(r))
	if err != nil {
		storeErr(w, err)
		return
	}
	writeJSON(w, http.StatusOK, map[string]any{"keys": keys})
}

// scope is the username a non-admin caller is confined to, and empty for an admin.
func scope(r *http.Request) string {
	sess := sessionFrom(r.Context())
	if sess.IsAdmin() {
		return ""
	}
	return sess.Username
}

func (s *Server) revokeKey(w http.ResponseWriter, r *http.Request) {
	id := r.PathValue("id")
	if err := s.st.RevokeKey(r.Context(), id, scope(r)); err != nil {
		storeErr(w, err)
		return
	}
	s.audit(r, "key.revoke", "", map[string]any{"key_id": id})
	writeJSON(w, http.StatusOK, map[string]any{"revoked": id})
}
