// Package auth handles argon2id password hashing and verification.
//
// Hashes use canonical PHC encoding with the same fixed resource profile as `lightship hash`.
package auth

import (
	"crypto/rand"
	"crypto/subtle"
	"encoding/base64"
	"errors"
	"fmt"
	"strings"

	"golang.org/x/crypto/argon2"
)

type params struct {
	memory  uint32
	time    uint32
	threads uint8
	keyLen  uint32
}

// Generated and imported hashes use 64 MiB, 3 iterations, 4 lanes and a 32-byte digest.
var defaults = params{memory: 64 * 1024, time: 3, threads: 4, keyLen: 32}

const (
	hashPrefix       = "$argon2id$v=19$m=65536,t=3,p=4$"
	saltBytes        = 16
	saltEncodedLen   = 22
	digestEncodedLen = 43
	hashEncodedLen   = len(hashPrefix) + saltEncodedLen + 1 + digestEncodedLen
)

var (
	ErrMismatch    = errors.New("password does not match")
	ErrInvalidHash = errors.New("invalid argon2id hash: use the profile generated by lightship hash")
)

func Hash(password string) (string, error) {
	salt := make([]byte, saltBytes)
	if _, err := rand.Read(salt); err != nil {
		return "", err
	}
	p := defaults
	key := argon2.IDKey([]byte(password), salt, p.time, p.memory, p.threads, p.keyLen)
	return fmt.Sprintf("$argon2id$v=%d$m=%d,t=%d,p=%d$%s$%s",
		argon2.Version, p.memory, p.time, p.threads,
		base64.RawStdEncoding.EncodeToString(salt),
		base64.RawStdEncoding.EncodeToString(key)), nil
}

// ValidateHash accepts only canonical Argon2id v19 PHC strings with m=65536,t=3,p=4,
// a 16-byte salt and a 32-byte digest. Validation never runs Argon2 or allocates from encoded
// parameters. The fixed 97-byte encoding bounds parsing before any base64 decoding.
func ValidateHash(encoded string) error {
	if len(encoded) != hashEncodedLen || !strings.HasPrefix(encoded, hashPrefix) ||
		encoded[len(hashPrefix)+saltEncodedLen] != '$' {
		return ErrInvalidHash
	}
	encoding := base64.RawStdEncoding.Strict()
	salt, err := encoding.DecodeString(encoded[len(hashPrefix) : len(hashPrefix)+saltEncodedLen])
	if err != nil || len(salt) != saltBytes {
		return ErrInvalidHash
	}
	digest, err := encoding.DecodeString(encoded[len(hashPrefix)+saltEncodedLen+1:])
	if err != nil || len(digest) != 32 {
		return ErrInvalidHash
	}
	return nil
}

// Verify validates the resource profile before hashing and compares the digest in constant time.
func Verify(password, encoded string) error {
	if err := ValidateHash(encoded); err != nil {
		return err
	}
	parts := strings.Split(encoded, "$")
	salt, _ := base64.RawStdEncoding.DecodeString(parts[4])
	want, _ := base64.RawStdEncoding.DecodeString(parts[5])
	p := defaults
	got := argon2.IDKey([]byte(password), salt, p.time, p.memory, p.threads, p.keyLen)
	if subtle.ConstantTimeCompare(got, want) != 1 {
		return ErrMismatch
	}
	return nil
}
